### ISSUE TITLE
Could you base this on the official redux-typescript template?

### ISSUE THREAD

**Issue by phryneas** [VladyslavMartynov/Aviasales_React-Redux-MobX-#1]
Hi, I'm a Redux maintainer.

Unfortunately, this (seemingly newly announced?) template is doing a lot things we are not teaching any more for a few years by now and as such has tons of boilerplate that is not really necessary in a modern Redux application.

Now, with the name being `typescript-redux` I fear that many people will accidentally install this instead of the official `redux-typescript` template and set themselves up with a lot of stuff that goes against our official recommendations.

Is there any way you could base this out on the official redux-typescript template and make clear in the README that it is not the official template?

Just to make sure what I mean by "more boilerplate":
Going by our recommendations, modern Redux applications do not have switch..case reducers, ACTION_TYPE strings, hand-written action creators, immutable reducer logic or TypeScript union action types. 
As a consequence, this repo is probably 5 times the code as going by our current recommendations would be - which is quite the difference.

I'd urge you to look at [the official template](https://github.com/reduxjs/cra-template-redux-typescript), this [short overview](https://redux.js.org/tutorials/fundamentals/part-8-modern-redux) and the [official Redux Essentials tutorial](https://redux.js.org/tutorials/essentials/part-1-overview-concepts) for a deeper dive.
Also, I'd recommend a look at the [Redux Style Guide](https://redux.js.org/style-guide/style-guide/).

**Comment by VladyslavMartynov** [comment]
Hey, yeah it was my fault and i currently agree with all things that you wrote.Nowadays it`s better to use Redux-Toolkit for global state rather than writing a lot of boiler code!

**Comment by phryneas** [comment]
Well, this is out now with the name `typescript-redux`, so could you please do some changes to it so unsuspecting people don't accidentally use it?

**Comment by VladyslavMartynov** [comment]
Hi, I am currently using RTK query data fetching, and I have some problems with pagination.I need to implement one functionality: when user refresh the data i set currentPage to initial page like in redux, and then use generatedHook using rtk but rtk returns me incorrect pagination page with incorrect data.I've been searched something that's really can help me in this situation, but documentation don't help me, maybe i should use optimistic updates or something else?

**Comment by phryneas** [comment]
I guess this is not really the right place for that - maybe ask on StackOverflow or in the #redux channel on reactiflux? In both cases with some code examples.
